name: flutter_multimodular_practice
packages:
  - core/**
  - features/**

command:
 bootstrap:
  environment:
    sdk: ^3.7.2
    flutter: ">=3.7.2 <4.0.0"
  dev_dependencies:
    # melos: ^6.3.2
    flutter_lints: ^5.0.0

  dependencies:
    cupertino_icons: ^1.0.8
    dio: ^5.8.0+1

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  test:
    run:  flutter test
  update: flutter pub outdated 
  upgrade: flutter pub upgrade --major-versions

