name: flutter_multimodular_practice
packages:
  - core/**
  - features/**

command:
 bootstrap:
  environment:
    sdk: ^3.7.2
    flutter: ">=3.7.2 <4.0.0"
  dev_dependencies:
    joson_serializable: ^6.9.4
    build_runner: ^2.4.6
    injectable_generator: ^2.7.0
    retrofit_generator: ^9.1.9

    # melos: ^6.3.2
    flutter_lints: ^5.0.0

  dependencies:
    cupertino_icons: ^1.0.8
    dio: ^5.8.0+1
    get_it: ^8.0.3
    injectable: ^2.5.0
    json_annotation: ^4.8.0
    pretty_dio_logger: ^1.2.0
    retrofit: ^4.4.2

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  test:
    run:  melos exec --concurrency=1 flutter test
  update: flutter pub outdated 
  upgrade: flutter pub upgrade --major-versions

